language: cpp

env:
  global:
    - LIBSTDC_VERSION=5

before_install:
  # Prepare compilers
  - sh scripts/install-gcc.sh

script:
  # Build with make
  - make clean
  - make
  - ./rarcrack --type zip test.zip

sudo: required

cache:
  - apt

